artifacts:
  - path: dist/*.exe
    name: Releases

build_script:
  - cmd: C:/Python38/python -m pip install pyinstaller==3.4.*
  - cmd: C:/Python38/python -m pip install .
  - cmd: C:/Python38/Scripts/pyinstaller.exe cappinstaller/__main__.py --onefile --uac-admin --noconsole -n gui

deploy:
  provider: GitHub
  auth_token:
    secure: PERK2LmRtPbgU6V1cL69AfLoMpyTsR9PogNG8UlXGMkNGHFlsIvDEaSy9yNOm4bb
  artifact: dist/gui.exe
  draft: false
  prerelease: false
  on:
    branch: master
