install:
   - cmd: git submodule update --init --recursive

artifacts:
  - path: dist/*.exe
    name: Releases

build_script:
  - cmd: C:/Python38/python -m pip install pyinstaller==3.1.*
  - cmd: C:/Python38/Scripts/pyinstaller.exe gui.py --onefile -p "cTk/ctk/" --uac-admin

deploy:
  provider: GitHub
  auth_token:
    secure: PERK2LmRtPbgU6V1cL69AfLoMpyTsR9PogNG8UlXGMkNGHFlsIvDEaSy9yNOm4bb
  artifact: dist/gui.exe
  draft: false
  prerelease: false
  on:
    branch: master
