artifacts:
  - path: dist/*.exe
    name: Releases

build_script:
  - cmd: git clone https://github.com/pyinstaller/pyinstaller --recursive && cd pyinstaller && git checkout v4.0 && cd bootloader && C:/Python38/python waf all --target-arch=32bit && cd .. && C:/Python38/python setup.py install && cd ..
  - cmd: C:/Python38/python -m pip install .
  - cmd: C:/Python38/Scripts/pyinstaller.exe cappinstaller/__main__.py --onefile --uac-admin --noconsole -n gui

deploy:
  provider: GitHub
  auth_token:
    secure: PERK2LmRtPbgU6V1cL69AfLoMpyTsR9PogNG8UlXGMkNGHFlsIvDEaSy9yNOm4bb
  artifact: dist/gui.exe
  draft: false
  prerelease: false
  on:
    branch: master
